QUESTIONS = {
   "Section 1: Logic": [
        {"q": "Pola angka: 2, 4, 8, 14, ?, 30. Angka selanjutnya?", "options": ["20", "22", "24", "26"], "answer": "22"},
        {"q": "Jika semua programmer adalah manusia, dan sebagian manusia suka kopi, apakah semua programmer suka kopi?", "options": ["Ya", "Mungkin", "Tidak", "Tidak dapat ditentukan"], "answer": "Tidak"},
        {"q": "Kereta bergerak 60 km/jam. Waktu tempuh untuk 180 km adalah...", "options": ["2 jam", "2.5 jam", "3 jam", "4 jam"], "answer": "3 jam"},
        {"q": "Semua laptop butuh listrik. MacBook adalah laptop. Jadi...", "options": ["MacBook tidak butuh listrik", "MacBook butuh listrik", "MacBook adalah komputer", "Semua salah"], "answer": "MacBook butuh listrik"},
        {"q": "Lengkapi pola: A, C, E, G, ?", "options": ["H", "I", "J", "K"], "answer": "I"},
        {"q": "Jika hari ini adalah Senin, maka 100 hari lagi adalah hari...", "options": ["Selasa", "Rabu", "Kamis", "Jumat"], "answer": "Selasa"},
        {"q": "Semua mahasiswa Teknik Informatika jago koding. Budi adalah mahasiswa Teknik Informatika. Budi tidak jago koding.", "options": ["Pernyataan Benar", "Pernyataan Salah", "Budi bukan mahasiswa TI", "Budi jago desain"], "answer": "Pernyataan Salah"},
        {"q": "Pola angka: 1, 1, 2, 3, 5, 8, ?", "options": ["10", "11", "12", "13"], "answer": "13"},
        {"q": "Andi lebih tua dari Budi. Cici lebih muda dari Budi. Siapa yang paling muda?", "options": ["Andi", "Budi", "Cici", "Tidak ada"], "answer": "Cici"},
        {"q": "Jika 'LAPTOP' ditulis sebagai 'MBOUPQ', maka 'BUKU' ditulis sebagai...", "options": ["CVLV", "CVLV", "CVLV", "CVLV"], "answer": "CVLV"}, # Pola: +1 huruf
        {"q": "Sebuah toko diskon 20%. Harga awal Rp 100.000. Berapa harga setelah diskon?", "options": ["Rp 70.000", "Rp 80.000", "Rp 90.000", "Rp 85.000"], "answer": "Rp 80.000"},
        {"q": "Manakah yang tidak termasuk kelompoknya?", "options": ["Swift", "Python", "Java", "HTML"], "answer": "HTML"},
        {"q": "Pola: 3, 6, 12, 24, ?", "options": ["36", "40", "48", "50"], "answer": "48"},
        {"q": "Jika beberapa dokter adalah musisi, dan semua musisi adalah kreatif. Maka...", "options": ["Semua dokter kreatif", "Beberapa dokter kreatif", "Tidak ada dokter kreatif", "Semua musisi adalah dokter"], "answer": "Beberapa dokter kreatif"},
        {"q": "Satu jam yang lalu adalah pukul 09.00. Pukul berapakah 3 jam dari sekarang?", "options": ["12.00", "13.00", "14.00", "15.00"], "answer": "13.00"},
        {"q": "Umur Ayah 3 kali umur Anaknya. Jika umur Anak 15 tahun, berapa umur Ayah 5 tahun lagi?", "options": ["45", "50", "55", "60"], "answer": "50"},
        {"q": "Pola: 100, 95, 85, 70, ?", "options": ["50", "55", "60", "65"], "answer": "50"},
        {"q": "Lengkapi analogi: Kertas : Kayu = Kain : ?", "options": ["Baju", "Kapas", "Benang", "Gunting"], "answer": "Kapas"},
        {"q": "Ada 5 orang mengantre. Eko di depan Dwi. Dwi di belakang Ani. Ani di belakang Budi. Siapa yang paling depan?", "options": ["Eko", "Dwi", "Ani", "Budi"], "answer": "Budi"},
        {"q": "Jika 5 mesin menghasilkan 5 alat dalam 5 menit, berapa waktu yang dibutuhkan 100 mesin untuk menghasilkan 100 alat?", "options": ["100 menit", "50 menit", "10 menit", "5 menit"], "answer": "5 menit"},
        {"q": "Manakah yang lebih berat: 1kg Kapas atau 1kg Besi?", "options": ["Kapas", "Besi", "Sama berat", "Tidak tahu"], "answer": "Sama berat"},
        {"q": "Lengkapi pola: 2, 6, 18, 54, ?", "options": ["108", "150", "162", "200"], "answer": "162"},
        {"q": "Jika semua mawar adalah bunga, dan beberapa bunga cepat layu. Apakah mawar cepat layu?", "options": ["Ya", "Tidak", "Belum tentu", "Tidak mungkin"], "answer": "Belum tentu"},
        {"q": "Berapa banyak angka 9 antara 1 sampai 100?", "options": ["10", "11", "19", "20"], "answer": "20"},
        {"q": "Jika p=3 dan q=4, maka nilai dari p^2 + q^2 adalah...", "options": ["7", "12", "25", "49"], "answer": "25"},
        {"q": "Pola angka: 5, 10, 20, 40, ?", "options": ["60", "70", "80", "90"], "answer": "80"},
        {"q": "Jika semua A adalah B, dan semua B adalah C, maka...", "options": ["Semua A adalah C", "Semua C adalah A", "Tidak bisa disimpulkan", "Semua B adalah A"], "answer": "Semua A adalah C"},
        {"q": "Pola angka: 1, 1, 2, 3, 5, ?", "options": ["6", "7", "8", "9"], "answer": "8"},
        {"q": "Jika 1 orang bisa menyelesaikan pekerjaan dalam 10 hari, maka 2 orang butuh berapa hari?", "options": ["5", "10", "15", "20"], "answer": "5"},
        {"q": "Pola huruf: B, E, H, K, ?", "options": ["M", "N", "O", "P"], "answer": "N"},
        {"q": "Jika harga 1 buku 5000, berapa harga 3 buku?", "options": ["10000", "15000", "20000", "25000"], "answer": "15000"},
        {"q": "Pola angka: 3, 9, 27, ?", "options": ["54", "72", "81", "90"], "answer": "81"},
        {"q": "Jika 10 pekerja menyelesaikan pekerjaan dalam 2 hari, maka 5 pekerja butuh berapa hari?", "options": ["2", "3", "4", "5"], "answer": "4"},
        {"q": "Pola angka: 100, 90, 80, 70, ?", "options": ["50", "55", "60", "65"], "answer": "60"}
    ],

   "Section 2: Programming (Swift Focus)": [
        {"q": "Output dari: let x = [1,2].map { $0 * 2 }", "options": ["[2, 4]", "[1, 2]", "[4, 2]", "Error"], "answer": "[2, 4]"},
        {"q": "Cara mendeklarasikan variabel yang nilainya bisa berubah di Swift?", "options": ["let", "var", "const", "static"], "answer": "var"},
        {"q": "Apa arti simbol '!' di belakang tipe data (misal String!)?", "options": ["Optional", "Implicitly Unwrapped Optional", "Force Close", "Error"], "answer": "Implicitly Unwrapped Optional"},
        {"q": "Fungsi array.filter { $0 % 2 == 0 } akan menghasilkan?", "options": ["Angka ganjil", "Angka genap", "Semua angka", "Jumlah angka"], "answer": "Angka genap"},
        {"q": "Manakah cara yang benar untuk menggabungkan string 'Hello' dan 'World' di Swift?", "options": ["'Hello' + 'World'", "'Hello' . 'World'", "'Hello' & 'World'", "concat('Hello', 'World')"], "answer": "'Hello' + 'World'"},
        {"q": "Apa kegunaan dari 'guard statement' di Swift?", "options": ["Untuk melakukan perulangan", "Untuk keluar dari fungsi lebih awal jika kondisi tidak terpenuhi", "Untuk membuat class", "Untuk menghapus variabel"], "answer": "Untuk keluar dari fungsi lebih awal jika kondisi tidak terpenuhi"},
        {"q": "Bagaimana cara mengecek jumlah elemen dalam array 'names'?", "options": ["names.length", "names.size", "names.count", "names.total"], "answer": "names.count"},
        {"q": "Apa fungsi dari keyword 'return' dalam sebuah fungsi?", "options": ["Mengulang fungsi", "Menghentikan program", "Mengembalikan nilai ke pemanggil fungsi", "Mencetak teks ke konsol"], "answer": "Mengembalikan nilai ke pemanggil fungsi"},
        {"q": "Manakah yang merupakan tipe data untuk angka desimal (presisi tinggi) di Swift?", "options": ["Int", "String", "Double", "Bool"], "answer": "Double"},
        {"q": "Operator '??' (Nil-Coalescing Operator) digunakan untuk?", "options": ["Memberikan nilai default jika optional bernilai nil", "Mengalikan dua angka", "Membandingkan dua string", "Force unwrap variabel"], "answer": "Memberikan nilai default jika optional bernilai nil"},
        {"q": "Apa output dari: print(5 / 2) jika keduanya adalah Integer?", "options": ["2.5", "2", "3", "Error"], "answer": "2"},
        {"q": "Keyword yang digunakan untuk menghentikan sebuah loop secara paksa adalah...", "options": ["stop", "exit", "break", "halt"], "answer": "break"},
        {"q": "Dalam Swift, 'String Interpolation' ditandai dengan simbol...", "options": ["${}", "{}", "\\()", "#()"], "answer": "\\()"},
        {"q": "Manakah loop yang mengevaluasi kondisi di akhir perulangan?", "options": ["for-in", "while", "repeat-while", "foreach"], "answer": "repeat-while"},
        {"q": "Tipe data yang hanya memiliki nilai true atau false adalah...", "options": ["Binary", "Boolean", "Logic", "Bit"], "answer": "Boolean"},
        {"q": "Apa kegunaan dari keyword 'lazy' pada variabel di Swift?", "options": ["Membuat variabel lambat diakses", "Variabel hanya dihitung saat pertama kali dipanggil", "Menghapus variabel dari memori", "Membuat variabel menjadi konstanta"], "answer": "Variabel hanya dihitung saat pertama kali dipanggil"},
        {"q": "Manakah koleksi di Swift yang tidak mengizinkan nilai duplikat?", "options": ["Array", "Dictionary", "Set", "Tuple"], "answer": "Set"},
        {"q": "Apa output dari code: print(type(of: 5.0))?", "options": ["Int", "Float", "Double", "Number"], "answer": "Double"},
        {"q": "Fungsi dari operator '===' (tiga sama dengan) adalah...", "options": ["Membandingkan nilai", "Memeriksa apakah dua referensi menunjuk ke instance class yang sama", "Memberikan nilai baru", "Memeriksa tipe data"], "answer": "Memeriksa apakah dua referensi menunjuk ke instance class yang sama"},
        {"q": "Bagaimana cara menambahkan elemen baru ke akhir sebuah Array?", "options": ["array.add(item)", "array.push(item)", "array.append(item)", "array.insert(item)"], "answer": "array.append(item)"},
        {"q": "Apa itu 'Tuple' di Swift?", "options": ["Tipe data untuk menyimpan satu nilai", "Grup berisi beberapa nilai dalam satu nilai majemuk", "Fungsi untuk melakukan looping", "Nama lain dari Class"], "answer": "Grup berisi beberapa nilai dalam satu nilai majemuk"},
        {"q": "Keyword 'defer' digunakan untuk...", "options": ["Menjalankan kode tepat sebelum fungsi berakhir", "Menunda eksekusi aplikasi", "Membatalkan proses download", "Membuat fungsi baru"], "answer": "Menjalankan kode tepat sebelum fungsi berakhir"},
        {"q": "Manakah cara benar untuk menulis komentar satu baris di Swift?", "options": ["# Komentar", "// Komentar", "/* Komentar", ""], "answer": "// Komentar"},
        {"q": "Apa arti 'mutating' pada sebuah fungsi di dalam Struct?", "options": ["Fungsi tidak bisa dipanggil", "Fungsi diperbolehkan mengubah nilai properti di dalam struct", "Fungsi akan menghapus struct", "Fungsi hanya untuk tampilan"], "answer": "Fungsi diperbolehkan mengubah nilai properti di dalam struct"},
        {"q": "Tipe data 'Any' di Swift berarti...", "options": ["Hanya bisa String", "Hanya bisa Integer", "Bisa mewakili instance dari tipe data apa pun", "Tidak boleh ada data"], "answer": "Bisa mewakili instance dari tipe data apa pun"}
    ],

   "Section 3: OOP": [
        {"q": "Apa perbedaan utama Struct dan Class di Swift?", "options": ["Struct reference type, Class value type", "Struct value type, Class reference type", "Keduanya sama saja", "Struct bisa inheritance"], "answer": "Struct value type, Class reference type"},
        {"q": "Konsep OOP yang menyembunyikan detail implementasi adalah...", "options": ["Inheritance", "Polymorphism", "Encapsulation", "Abstraction"], "answer": "Encapsulation"},
        {"q": "Keyphrase 'override' digunakan untuk...", "options": ["Membuat fungsi baru", "Menimpa fungsi dari parent class", "Menghapus fungsi", "Menjalankan fungsi"], "answer": "Menimpa fungsi dari parent class"},
        {"q": "Apa yang dimaksud dengan Inheritance (Pewarisan)?", "options": ["Kemampuan class untuk menurunkan sifat ke class lain", "Kemampuan menyembunyikan data", "Proses pembuatan objek", "Cara menghapus class"], "answer": "Kemampuan class untuk menurunkan sifat ke class lain"},
        {"q": "Di Swift, sebuah class hanya bisa mewarisi dari berapa superclass?", "options": ["Satu", "Dua", "Tidak terbatas", "Tergantung RAM"], "answer": "Satu"},
        {"q": "Apa kegunaan dari 'init' di dalam sebuah class Swift?", "options": ["Mengakhiri program", "Menghapus data", "Proses inisialisasi/persiapan nilai awal", "Menghubungkan ke database"], "answer": "Proses inisialisasi/persiapan nilai awal"},
        {"q": "Polymorphism memungkinkan kita untuk...", "options": ["Menggunakan satu interface untuk berbagai tipe data", "Membuat class menjadi sangat besar", "Mengunci variabel agar tidak bisa diubah", "Mempercepat koneksi internet"], "answer": "Menggunakan satu interface untuk berbagai tipe data"},
        {"q": "Manakah keyword yang digunakan agar sebuah class tidak bisa diwariskan lagi?", "options": ["static", "final", "private", "locked"], "answer": "final"},
        {"q": "Apa perbedaan 'Property' dan 'Method' dalam sebuah objek?", "options": ["Property itu fungsi, Method itu data", "Property itu data/atribut, Method itu perilaku/fungsi", "Sama saja", "Property hanya untuk class"], "answer": "Property itu data/atribut, Method itu perilaku/fungsi"},
        {"q": "Apa yang terjadi pada memory jika kita menggunakan 'Reference Type'?", "options": ["Data disalin ke variabel baru", "Kedua variabel menunjuk ke alamat memory yang sama", "Memory langsung penuh", "Data dihapus otomatis"], "answer": "Kedua variabel menunjuk ke alamat memory yang sama"},
        {"q": "Apa yang dimaksud dengan 'Deinitializer' (deinit) di Swift?", "options": ["Fungsi untuk membuat objek", "Fungsi yang dipanggil tepat sebelum sebuah class instance dihapus dari memori", "Fungsi untuk menyalin data", "Fungsi untuk mengupdate UI"], "answer": "Fungsi yang dipanggil tepat sebelum sebuah class instance dihapus dari memori"},
        {"q": "Manakah pernyataan yang benar tentang 'Computed Property'?", "options": ["Hanya menyimpan nilai statis", "Nilainya dihitung setiap kali properti tersebut diakses", "Sama dengan konstanta 'let'", "Hanya bisa digunakan di dalam class"], "answer": "Nilainya dihitung setiap kali properti tersebut diakses"},
        {"q": "Konsep 'Abstraction' bertujuan untuk...", "options": ["Membuat kode jadi lebih panjang", "Menampilkan fungsionalitas penting dan menyembunyikan detail kompleksitas", "Menghubungkan aplikasi ke server", "Menghapus bug secara otomatis"], "answer": "Menampilkan fungsionalitas penting dan menyembunyikan detail kompleksitas"},
        {"q": "Di Swift, apa kegunaan dari keyword 'super'?", "options": ["Membuat class menjadi super", "Mengakses method atau property dari parent class", "Mempercepat performa aplikasi", "Keluar dari aplikasi"], "answer": "Mengakses method atau property dari parent class"},
        {"q": "Apa perbedaan antara 'Static Method' dan 'Instance Method'?", "options": ["Static dipanggil pada class itu sendiri, Instance dipanggil pada objek hasil cetakan class", "Instance lebih cepat dari Static", "Static hanya untuk angka", "Tidak ada perbedaan"], "answer": "Static dipanggil pada class itu sendiri, Instance dipanggil pada objek hasil cetakan class"},
        {"q": "Apa kegunaan dari 'Protocol' di Swift?", "options": ["Sebagai blueprint untuk method atau property yang harus diimplementasikan", "Untuk mengatur koneksi internet", "Untuk menyimpan data user", "Untuk mengganti tema aplikasi"], "answer": "Sebagai blueprint untuk method atau property yang harus diimplementasikan"},
        {"q": "Istilah untuk sebuah class yang mewarisi sifat dari class lain adalah...", "options": ["Superclass", "Subclass", "Rootclass", "Baseclass"], "answer": "Subclass"},
        {"q": "Manakah yang merupakan pilar utama OOP?", "options": ["Encapsulation, Inheritance, Polymorphism, Abstraction", "Array, List, Set, Dictionary", "Swift, Objective-C, Java, Python", "Variables, Functions, Loops, Conditions"], "answer": "Encapsulation, Inheritance, Polymorphism, Abstraction"},
        {"q": "Apa yang dimaksud dengan 'Optional Chaining'?", "options": ["Proses menyambungkan beberapa kabel", "Proses pemanggilan property/method pada optional yang mungkin bernilai nil", "Looping di dalam optional", "Cara menghapus variabel optional"], "answer": "Proses pemanggilan property/method pada optional yang mungkin bernilai nil"},
        {"q": "Apa fungsi dari keyword 'self'?", "options": ["Merujuk pada instance dari class/struct itu sendiri", "Menutup aplikasi", "Membuat salinan class", "Mencetak nama variabel"], "answer": "Merujuk pada instance dari class/struct itu sendiri"}
    ],

    "Section 4: Bonus (Design/UX)": [
        {"q": "Prinsip utama Apple dalam UI Design adalah HIG. Apa singkatannya?", "options": ["High Interface Guide", "Human Interface Guidelines", "Helpful Interface Graphics", "Human Integrated Goal"], "answer": "Human Interface Guidelines"},
        {"q": "Fitur paling krusial untuk aplikasi booking coworking space adalah...", "options": ["Filter harga & fasilitas", "Background warna-warni", "Animasi berat", "Chat bot"], "answer": "Filter harga & fasilitas"},
        {"q": "Dalam desain UI, apa yang dimaksud dengan 'Affordance'?", "options": ["Biaya pembuatan desain", "Petunjuk visual yang menunjukkan cara penggunaan suatu objek", "Kecepatan loading gambar", "Warna yang mencolok"], "answer": "Petunjuk visual yang menunjukkan cara penggunaan suatu objek"},
        {"q": "Mana yang merupakan prinsip desain 'Consistency' menurut Apple?", "options": ["Menggunakan font yang berbeda di setiap halaman", "Menggunakan simbol dan gaya yang sama di seluruh aplikasi", "Mengubah posisi menu utama sesuka hati", "Menghapus tombol navigasi"], "answer": "Menggunakan simbol dan gaya yang sama di seluruh aplikasi"},
        {"q": "Apa tujuan utama dari 'User Research' sebelum membuat aplikasi?", "options": ["Menentukan harga aplikasi", "Memahami kebutuhan, perilaku, dan masalah pengguna", "Mencari investor", "Menghitung jumlah baris kodingan"], "answer": "Memahami kebutuhan, perilaku, dan masalah pengguna"},
        {"q": "Apa itu 'Dark Mode' dalam konteks UX?", "options": ["Aplikasi hanya bisa dibuka malam hari", "Skema warna gelap yang mengurangi kelelahan mata", "Mode aplikasi saat tidak ada internet", "Fitur untuk menyembunyikan data"], "answer": "Skema warna gelap yang mengurangi kelelahan mata"},
        {"q": "Prinsip 'Feedback' dalam UI berarti...", "options": ["Memberi tahu user hasil dari aksi yang mereka lakukan", "Meminta rating di App Store setiap menit", "Menghubungi customer service", "Menunggu balasan email"], "answer": "Memberi tahu user hasil dari aksi yang mereka lakukan"},
        {"q": "Apa yang dimaksud dengan 'Accessibility' (Aksesibilitas) pada aplikasi?", "options": ["Kemudahan akses download", "Desain yang bisa digunakan oleh semua orang, termasuk penyandang disabilitas", "Keamanan kata sandi", "Ukuran file yang kecil"], "answer": "Desain yang bisa digunakan oleh semua orang, termasuk penyandang disabilitas"},
        {"q": "Dalam prinsip Apple, 'Clarity' berarti...", "options": ["Teks harus bisa dibaca dan ikon harus bermakna jelas", "Layar harus sangat terang", "Aplikasi harus transparan", "Menggunakan banyak gambar dekoratif"], "answer": "Teks harus bisa dibaca dan ikon harus bermakna jelas"},
        {"q": "Mana yang merupakan contoh 'Bad UX'?", "options": ["Navigasi yang mudah ditemukan", "Tombol yang terlalu kecil dan sulit diklik", "Waktu loading yang cepat", "Bahasa yang mudah dimengerti"], "answer": "Tombol yang terlalu kecil dan sulit diklik"}
    ]
    
}